name: Deploy to Dev

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    environment:
      name: firebase
      url: https://workshop0406-36c8b.web.app
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm ci

      - name: Build React
        run: npm run build

      - name: Deploy to Firebase
        run: npm i -g firebase-tools@latest
      - run: firebase deploy --token "$FIREBASE_TOKEN"  
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN}}  
    